"""add role column to users

Revision ID: 0adbd2dbee3b
Revises: c59f09d24c1d
Create Date: 2026-01-15 22:47:58.084869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0adbd2dbee3b'
down_revision: Union[str, Sequence[str], None] = 'c59f09d24c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'role',
        sa.String(length=20),
        nullable=False,
        server_default='user'
      )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
